### PR TITLE
New cameras

### PR DESCRIPTION
**Pull request by LeeHudsonDLS**
New camera XMLs added

### CODE REVIEW

**Comment by MarkRivers** [comment]
What camera model did Prosilica_GC.xml come from? Are all models the same? 

I updated a GC1380H to the latest firmware yesterday and extracted into AVT_GC1380H.xml. Can you compare that to your file?

**Comment by MarkRivers** [comment]
I have compared the start of the xml files for your new Prosilica_GC.xml and the AVT_GC1380.xml I created yesterday.

Prosilica_GC.xml (blank lines removed)
```
corvette:areaDetector/ADGenICam/xml>head -30 Prosilica_GC.xml
<?xml version="1.0" encoding="utf-8"?>
<RegisterDescription
 ModelName="GECCDSTD"
 VendorName="Prosilica"
 StandardNameSpace="None"
 SchemaMajorVersion="1"
 SchemaMinorVersion="0"
 SchemaSubMinorVersion="1"
 MajorVersion="298"
 MinorVersion="2"
 SubMinorVersion="0"
```

AVT_GC1380H.xml
```
corvette:areaDetector/ADGenICam/xml>head -30 AVT_GC1380H.xml
<?xml version="1.0" encoding="utf-8"?>
<RegisterDescription
    ModelName="GECCDSTD"
    VendorName="Allied_Vision_Technologies"
    StandardNameSpace="None"
    SchemaMajorVersion="1"
    SchemaMinorVersion="0"
    SchemaSubMinorVersion="1"
    MajorVersion="306"
    MinorVersion="1"
    SubMinorVersion="0"
```

Note that Prosilica_GC.xml is MajorVersion=298 while AVT_GC1380H.xml is 306.  I believe this is because I installed the latest firmware version from AVT (1.50.1).  

We need to decide how to handle firmware versions.  I think the policy should be that the versions in ADGenICam should be for the most recent firmware version for that camera, because it is easy to update firmware versions.

@LeeHudsonDLS can you update your camera to the latest firmware version and see if the xml file is then the same as mine?

**Comment by LeeHudsonDLS** [comment]
@MarkRivers , It was a colleague that added that specific camera so i will check the exact model today. I suspect we won't be able to update the firmware until the next shutdown though. I will see if I can get access today.

**Comment by LeeHudsonDLS** [comment]
@MarkRivers , The camera in question was an AVT Prosilica GE1050C. I'll see about getting the firmware updated and check the new xml.

**Comment by MarkRivers** [comment]
According to AVT's Website the most recent firmware for that camera is 1.43.05 from June 2011.
https://cdn.alliedvision.com/fileadmin/content/documents/products/software/firmware/Allied_Vision_GigE_Firmware_Release_Notes_00.01.54.20339.pdf

I don't think that xml file should be called Prosilica_GC.xml since it is for a GE, not, GC, and is for very old firmware. There are many GC cameras with much newer firmware.

**Comment by LeeHudsonDLS** [comment]
I agree, i'll rename it. The current name doesn't make allot of sense.

**Pull request merged**
