### PR TITLE
Script modified to use correct PV names as in makeEdl.py

### PR DESCRIPTION
**Pull request by LeeHudsonDLS**
I'm in the process of getting ADGenICam and ADAravis working at diamond and I noticed the script makeEdl.py wasn't using the same PV names as the makeAdl.py script. I've copied the logic across.

### CODE REVIEW

**Comment by MarkRivers** [comment]
That makeEdl.py file in ADGenICam is basically just the makeDbAndEdl.py from aravisGigE with the database building removed.  I have not done anything else to it.  In addition to changing the PV names you might consider building multiple smaller screens as I do with makeAdl.py.  You can also make edl files by first make adl files and then runnning the converter.  It does a pretty good job now.

**Comment by MarkRivers** [comment]
I just want to make sure you know that there is an ADAravis.edl and all of the camera-specific smaller screens for edm in the [ADGenICam](https://github.com/areaDetector/ADGenICam/tree/master/GenICamApp/op/edl/autoconvert) directory.  Have you tried those screens?

**Comment by LeeHudsonDLS** [comment]
Yes i've just given them a go. I wonder if there's any point in modifying the makeEdl.py script if I can just use the makeAdl.py script and run the converter (probably what you were getting at)? Perhaps having 2 scripts doing very similar things will make it hard work for maintenance. I'll do some more testing with the converter, if I find I don't need to modify them then I see no reason not to use the converter.

**Comment by MarkRivers** [comment]
If we can eliminate the make Edl.py script that will make it easier to maintain.  The autoconverted files seem to look pretty good now.

**Comment by LeeHudsonDLS** [comment]
Ok I'll do abit of testing today and tomorrow.

**Comment by LeeHudsonDLS** [comment]
Hi Mark, I think it should be fine to get rid of makeEdl.py entirely, i'm using the makeAdl.py script and converting using adl2edl as suggest and it looks fine.

**Pull request closed without merging**
