### PR TITLE
Adding files for allied vision 1800 u811m camera

### PR DESCRIPTION
**Pull request by jwlodek**
Adding files for allied vision 1800 u811m camera

Ran into the following generating said files:

```
[jwlodek@xf28idd-ioc1 scripts]$ python3 makeDb.py ../xml/Allied_Vision_1800_U-811m.xml test.template
Don't know what to do with String
Don't know what to do with String
Don't know what to do with String
Don't know what to do with String
Don't know what to do with String
Don't know what to do with String
Don't know what to do with String
More than 16 enum entries for PixelFormat mbbi record, discarding additional options.
   If needed, edit the Enumeration tag for PixelFormat to select the 16 you want.
More than 16 enum entries for LineSource mbbi record, discarding additional options.
   If needed, edit the Enumeration tag for LineSource to select the 16 you want.
Don't know what to do with Register
More than 16 enum entries for CustomConvolutionValueSelector mbbi record, discarding additional options.
   If needed, edit the Enumeration tag for CustomConvolutionValueSelector to select the 16 you want.
```

Also needed to build a newer version of aravis and the arv-tool to get "String" features to work correctly - most likely a new addition to the standard?

### CODE REVIEW

**Comment by MarkRivers** [comment]
What are String features used for?  Should we be creating records and OPI screen widgets for String features?

**Comment by MarkRivers** [comment]
> Also needed to build a newer version of aravis and the arv-tool to get "String" features to work correctly - most likely a new addition to the standard?

What version of aravis did you use?

**Comment by jwlodek** [comment]
I built the master branch of Aravis from github, but I believe the relevant commits/PR is here: https://github.com/AravisProject/aravis/pull/508

The older installation of aravis v0.8 did not handle the String features correctly. I am fairly sure this is a GenICam standard, or at least that is how the aravis maintainers have mentioned it. In this case I was trying to find the camera Serial Number, which was labelled as a "String" feature, and didn't appear to arv-tool till I upgraded.

**Comment by MarkRivers** [comment]
I just looked at the aravis release notes.  GenICam String support was added in ARAVIS_0_8_10 on may 12, 2021.  The current release is 0.8.21.

**Pull request merged**
